apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullName" . }}-secret
  labels: {{- include "chart.labels" . | nindent 4 }}
stringData:
  DB_USER: '{{ .Values.app.database.dbuser }}'
  DB_PASSWORD: '{{ .Values.app.database.dbpassword }}'
  GMAIL_PASSWORD: '{{ .Values.app.emailNotification.gmailPassword }}'
