apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullName" . }}-secret
  labels: {{- include "chart.labels" . | nindent 4 }}
stringData:
  postgres-user: "{{ .Values.app.dbUserName }}"
  postgres-password: "{{ .Values.app.dbUserPass }}"
